FROM ruby:3.4.3

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    libpq-dev \
    nodejs \
    yarn \
    git \
    curl \
    libjemalloc2 \
    libvips \
    postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /app

# Copy both Gemfile and Gemfile.lock at once before installing
COPY Gemfile Gemfile.lock ./

# Install gems only once
RUN bundle install

# Copy the rest of the app
COPY . .

CMD ["bash"]
