FROM ruby:3.4.3

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  yarn \
  git \
  curl

WORKDIR /app

# Copy both Gemfile and Gemfile.lock at once before installing
COPY Gemfile Gemfile.lock ./

# Install gems only once
RUN bundle install

# Copy the rest of the app
COPY . .

CMD ["bash"]
