services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: bash -c "bundle install && bin/dev"
    tty: true
    stdin_open: true
    environment:
      - TAILWINDCSS_WATCH_POLL=true   # 👈 This line is key!
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mahini_development

volumes:
  pgdata:
